version: '3.8'

services:
  swiftapigraphql:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - '8001:8001'
    networks:
      - public
      - private
    environment:
      - DATABASE_URL = 'sqlite://'

networks:
  public:
  private:
